#!/bin/bash

# This script strips osgt files (produced by osgexport)
# of unnecessary node hierarchy, leaving only osg::Geode.

fileName=$1

if [ -z "$fileName" ]; then
    echo "Usage: $0 FILE_NAME"
    exit 1
fi

# Create temporary directory for temporary files.
MYTMPDIR=$(mktemp -d)
# Remove temporary directory on exit.
trap "rm -fR $MYTMPDIR" EXIT

tmpFileNameA=$MYTMPDIR/strip-osgt.tmp.a
tmpFileNameB=$MYTMPDIR/strip-osgt.tmp.b

# 1. Replace '\n' to '\r' for sed to work easily.
# Topic: How can I use sed to replace a multi-line string?
# Source: https://unix.stackexchange.com/a/152389
cat $fileName | tr '\n' '\r' > $tmpFileNameA

# 2. Remove StateSet.
cat $tmpFileNameA | sed 's|StateSet.*PrimitiveSet|PrimitiveSet|' > $tmpFileNameB

# 3. Strip Geode parents.
# 3.1. Strip header.
cat $tmpFileNameB | sed 's|osg::Group.*osg::Geode|osg::Geode|' > $tmpFileNameA
# 3.1. Strip footer.
cat $tmpFileNameA | sed 's|}.      Matrix {.*||' > $tmpFileNameB

# 4. Replace '\r' back to '\n'.
cat $tmpFileNameB | tr '\r' '\n'
